    - name: Check for Dataout files
      run: |
        if ls Dataout/*.csv 1> /dev/null 2>&1; then
          echo "Files found."
        else
          echo "No files found in Dataout directory."
          exit 1
        fi